# Generated by Django 3.2.9 on 2021-11-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VettingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=240)),
                ('website', models.CharField(max_length=240)),
                ('avatar_url', models.CharField(max_length=240)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vetter_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VetterDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_url', models.CharField(max_length=240)),
                ('avatar', models.URLField(max_length=240)),
                ('email', models.EmailField(max_length=240)),
                ('location', models.CharField(max_length=120)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
