# Generated by Django 3.2.9 on 2021-11-17 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0008_remove_repomodel_discussion_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetting', '0003_auto_20211116_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='VettingURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_url', models.CharField(max_length=240)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_url_to_user', to=settings.AUTH_USER_MODEL)),
                ('repo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetting_url_to_repo', to='contributor.repomodel')),
            ],
        ),
    ]
