# Generated by Django 3.2.9 on 2021-11-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetting', '0004_vettingurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VettingURL',
        ),
    ]
