# Generated by Django 3.2.9 on 2021-11-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributor', '0010_repomodel_stars'),
        ('vetting', '0005_delete_vettingurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_url', models.CharField(max_length=240)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_url_to_user', to=settings.AUTH_USER_MODEL)),
                ('repo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_url_to_repo', to='contributor.repomodel')),
            ],
        ),
    ]
