# Generated by Django 3.2.9 on 2021-11-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('git_url', models.CharField(max_length=240)),
                ('git_commit', models.CharField(max_length=240)),
                ('upvotes', models.PositiveIntegerField()),
                ('downvotes', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
