# Generated by Django 3.2.9 on 2021-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='signed_off',
            field=models.BooleanField(default=False),
        ),
    ]
