# Generated by Django 3.2.9 on 2021-11-12 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributor', '0002_repomodel_signed_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='module_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='repomodel',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repomodel',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=12)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_to_contributor', to=settings.AUTH_USER_MODEL)),
                ('repo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_to_repository', to='contributor.repomodel')),
            ],
        ),
    ]
