# Generated by Django 3.2.9 on 2021-11-14 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0003_auto_20211112_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
