# Generated by Django 3.2.9 on 2021-11-14 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributor', '0004_devices_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repomodel',
            old_name='git_url',
            new_name='git_repo',
        ),
        migrations.AddField(
            model_name='repomodel',
            name='git_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repomodel',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
