# Generated by Django 3.2.9 on 2021-11-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0006_repomodel_discussion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='module_version',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
