# Generated by Django 3.2.9 on 2021-11-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0007_repomodel_module_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repomodel',
            name='discussion_url',
        ),
    ]
