# Generated by Django 3.2.9 on 2021-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0008_remove_repomodel_discussion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='discussion_url',
            field=models.URLField(blank=True, max_length=240, null=True),
        ),
    ]
