# Generated by Django 3.2.9 on 2021-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0009_repomodel_discussion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
