# Generated by Django 3.2.9 on 2021-11-14 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributor', '0005_auto_20211114_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upvoted', models.BooleanField(default=False)),
                ('downvoted', models.BooleanField(default=False)),
                ('unsure', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_repository', to='contributor.repomodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoWeekVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upvoted', models.BooleanField(default=False)),
                ('downvoted', models.BooleanField(default=False)),
                ('unsure', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_week_user_to_repository', to='contributor.repomodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_week_vote_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
