# Generated by Django 3.2.9 on 2021-11-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='repo_model',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='TwoWeekVote',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
